name = "pager-relay"
main = "src/index.ts"
compatibility_date = "2024-12-01"
account_id = "0f56ad2619afc619cc2975dd0728f8a9"

[vars]
APNS_BUNDLE_ID = "sh.saqoo.pager-app"
APNS_KEY_ID = "SRH3669YH6"
APNS_TEAM_ID = "VCFY2GFR89"
APNS_USE_SANDBOX = "false"

[[kv_namespaces]]
binding = "REQUESTS"
id = "47152719f9a743f48c25bef951cb1352"

