import Foundation

/// A single captured notification, shared between the main app and the
/// Notification Service Extension via the App Group container.
struct NotificationHistoryItem: Codable, Identifiable, Hashable, Sendable {
    /// Stable identifier. Equals `requestId` for permission requests,
    /// otherwise a UUID generated by the extension.
    let id: String
    let receivedAt: Date
    let title: String
    /// Full body. For `/request`, taken from the custom `toolInputFull`
    /// key. For `/notify`, taken from `aps.alert.body`.
    let body: String
    let category: String?
    let project: String?
    let toolName: String?
    let requestId: String?
    var decision: String?
    var decidedAt: Date?

    init(
        id: String,
        receivedAt: Date,
        title: String,
        body: String,
        category: String? = nil,
        project: String? = nil,
        toolName: String? = nil,
        requestId: String? = nil,
        decision: String? = nil,
        decidedAt: Date? = nil
    ) {
        self.id = id
        self.receivedAt = receivedAt
        self.title = title
        self.body = body
        self.category = category
        self.project = project
        self.toolName = toolName
        self.requestId = requestId
        self.decision = decision
        self.decidedAt = decidedAt
    }
}
