import Foundation

/// A single captured notification, shared between the main app and the
/// Notification Service Extension via the App Group container.
struct NotificationHistoryItem: Codable, Identifiable, Hashable, Sendable {
    /// Stable identifier. Equals `requestId` for permission requests,
    /// otherwise a UUID generated by the extension.
    let id: String
    let receivedAt: Date
    let title: String
    /// Full body. For `/request`, taken from the custom `toolInputFull`
    /// key. For `/notify`, taken from `aps.alert.body`.
    let body: String
    let category: String?
    let project: String?
    let toolName: String?
    let requestId: String?
    /// Optional CLI identifier (`claude` / `codex` / `cursor`) so the main
    /// app can render the matching avatar in the history list. Optional
    /// because items written before this field was added need to decode.
    let source: String?
    var decision: String?
    var decidedAt: Date?

    init(
        id: String,
        receivedAt: Date,
        title: String,
        body: String,
        category: String? = nil,
        project: String? = nil,
        toolName: String? = nil,
        requestId: String? = nil,
        source: String? = nil,
        decision: String? = nil,
        decidedAt: Date? = nil
    ) {
        self.id = id
        self.receivedAt = receivedAt
        self.title = title
        self.body = body
        self.category = category
        self.project = project
        self.toolName = toolName
        self.requestId = requestId
        self.source = source
        self.decision = decision
        self.decidedAt = decidedAt
    }

    /// Jq and some pipelines pass through the four ASCII letters `null` as the
    /// string when a JSON `null` is stringified. Treat that as no body for display.
    static func displayableBody(_ body: String) -> String {
        if body == "null" { return "" }
        return body
    }

}
